// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhvu9mSC1Gc_5A40siAAwSNzaMVYFW50',
    appId: '1:170065725428:web:e152e2378f6c07c21b5ba1',
    messagingSenderId: '170065725428',
    projectId: 'hitster-game',
    authDomain: 'hitster-game.firebaseapp.com',
    storageBucket: 'hitster-game.firebasestorage.app',
    measurementId: 'G-QT1R2V8KP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY00NYFU4ZVdC4HUNGP6UNronizpzBsno',
    appId: '1:170065725428:android:b2d8844e754b7a3b1b5ba1',
    messagingSenderId: '170065725428',
    projectId: 'hitster-game',
    storageBucket: 'hitster-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEIwoDanZzhiz194B42FXkaFDZor2g0R8',
    appId: '1:170065725428:ios:9eb5efaf84d5e4b71b5ba1',
    messagingSenderId: '170065725428',
    projectId: 'hitster-game',
    storageBucket: 'hitster-game.firebasestorage.app',
    iosBundleId: 'com.zviki.hitster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEIwoDanZzhiz194B42FXkaFDZor2g0R8',
    appId: '1:170065725428:ios:9eb5efaf84d5e4b71b5ba1',
    messagingSenderId: '170065725428',
    projectId: 'hitster-game',
    storageBucket: 'hitster-game.firebasestorage.app',
    iosBundleId: 'com.zviki.hitster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMhvu9mSC1Gc_5A40siAAwSNzaMVYFW50',
    appId: '1:170065725428:web:2d744a165c209b131b5ba1',
    messagingSenderId: '170065725428',
    projectId: 'hitster-game',
    authDomain: 'hitster-game.firebaseapp.com',
    storageBucket: 'hitster-game.firebasestorage.app',
    measurementId: 'G-RPXZS90Y02',
  );
}
